export interface UCSEntry {
  category: string;
  subCategory: string;
  catId: string;
}

export const UCS_CATEGORIES: UCSEntry[] = [
  { category: 'AIR', subCategory: 'BLOW', catId: 'AIRBlow' },
  { category: 'AIR', subCategory: 'BURST', catId: 'AIRBrst' },
  { category: 'AIR', subCategory: 'HISS', catId: 'AIRHiss' },
  { category: 'AIR', subCategory: 'MISC', catId: 'AIRMisc' },
  { category: 'AIR', subCategory: 'SUCTION', catId: 'AIRSuck' },
  { category: 'AIRCRAFT', subCategory: 'DOOR', catId: 'AERODoor' },
  { category: 'AIRCRAFT', subCategory: 'HELICOPTER', catId: 'AEROHeli' },
  { category: 'AIRCRAFT', subCategory: 'INTERIOR', catId: 'AEROInt' },
  { category: 'AIRCRAFT', subCategory: 'JET', catId: 'AEROJet' },
  { category: 'AIRCRAFT', subCategory: 'MECHANISM', catId: 'AEROMech' },
  { category: 'AIRCRAFT', subCategory: 'MILITARY', catId: 'AEROMil' },
  { category: 'AIRCRAFT', subCategory: 'MISC', catId: 'AEROMisc' },
  { category: 'AIRCRAFT', subCategory: 'PROP', catId: 'AEROProp' },
  { category: 'AIRCRAFT', subCategory: 'RADIO CONTROLLED', catId: 'AERORadio' },
  { category: 'AIRCRAFT', subCategory: 'ROCKET', catId: 'AERORckt' },
  { category: 'ALARMS', subCategory: 'BELL', catId: 'ALRMBell' },
  { category: 'ALARMS', subCategory: 'BUZZER', catId: 'ALRMBuzr' },
  { category: 'ALARMS', subCategory: 'CLOCK', catId: 'ALRMClok' },
  { category: 'ALARMS', subCategory: 'ELECTRONIC', catId: 'ALRMElec' },
  { category: 'ALARMS', subCategory: 'MISC', catId: 'ALRMMisc' },
  { category: 'ALARMS', subCategory: 'SIREN', catId: 'ALRMSirn' },
  { category: 'AMBIENCE', subCategory: 'AIR', catId: 'AMBAir' },
  { category: 'AMBIENCE', subCategory: 'ALPINE', catId: 'AMBAlpn' },
  { category: 'AMBIENCE', subCategory: 'AMUSEMENT', catId: 'AMBAmus' },
  { category: 'AMBIENCE', subCategory: 'BIRDSONG', catId: 'AMBBird' },
  { category: 'AMBIENCE', subCategory: 'CELEBRATION', catId: 'AMBCele' },
  { category: 'AMBIENCE', subCategory: 'CONSTRUCTION', catId: 'AMBCnst' },
  { category: 'AMBIENCE', subCategory: 'DESERT', catId: 'AMBDsrt' },
  { category: 'AMBIENCE', subCategory: 'DESIGNED', catId: 'AMBDsgn' },
  { category: 'AMBIENCE', subCategory: 'EMERGENCY', catId: 'AMBEmrg' },
  { category: 'AMBIENCE', subCategory: 'FANTASY', catId: 'AMBFant' },
  { category: 'AMBIENCE', subCategory: 'FARM', catId: 'AMBFarm' },
  { category: 'AMBIENCE', subCategory: 'FOREST', catId: 'AMBForst' },
  { category: 'AMBIENCE', subCategory: 'GRASSLAND', catId: 'AMBGras' },
  { category: 'AMBIENCE', subCategory: 'HISTORICAL', catId: 'AMBHist' },
  { category: 'AMBIENCE', subCategory: 'HITECH', catId: 'AMBTech' },
  { category: 'AMBIENCE', subCategory: 'HOSPITAL', catId: 'AMBHosp' },
  { category: 'AMBIENCE', subCategory: 'INDUSTRIAL', catId: 'AMBInd' },
  { category: 'AMBIENCE', subCategory: 'INSECT', catId: 'AMBInsc' },
  { category: 'AMBIENCE', subCategory: 'LAKESIDE', catId: 'AMBLake' },
  { category: 'AMBIENCE', subCategory: 'MARKET', catId: 'AMBMrkt' },
  { category: 'AMBIENCE', subCategory: 'MISC', catId: 'AMBMisc' },
  { category: 'AMBIENCE', subCategory: 'NAUTICAL', catId: 'AMBNaut' },
  { category: 'AMBIENCE', subCategory: 'OFFICE', catId: 'AMBOffc' },
  { category: 'AMBIENCE', subCategory: 'PARK', catId: 'AMBPark' },
  { category: 'AMBIENCE', subCategory: 'PRISON', catId: 'AMBPrisn' },
  { category: 'AMBIENCE', subCategory: 'PROTEST', catId: 'AMBPrtst' },
  { category: 'AMBIENCE', subCategory: 'PUBLIC PLACE', catId: 'AMBPubl' },
  { category: 'AMBIENCE', subCategory: 'RELIGIOUS', catId: 'AMBRlgn' },
  { category: 'AMBIENCE', subCategory: 'RESIDENTIAL', catId: 'AMBHome' },
  { category: 'AMBIENCE', subCategory: 'RESTAURANT & BAR', catId: 'AMBRest' },
  { category: 'AMBIENCE', subCategory: 'ROOM TONE', catId: 'AMBRoom' },
  { category: 'AMBIENCE', subCategory: 'RURAL', catId: 'AMBRurl' },
  { category: 'AMBIENCE', subCategory: 'SCHOOL', catId: 'AMBSchl' },
  { category: 'AMBIENCE', subCategory: 'SCIFI', catId: 'AMBSci' },
  { category: 'AMBIENCE', subCategory: 'SEASIDE', catId: 'AMBSea' },
  { category: 'AMBIENCE', subCategory: 'SPORT', catId: 'AMBSprt' },
  { category: 'AMBIENCE', subCategory: 'SUBURBAN', catId: 'AMBSubn' },
  { category: 'AMBIENCE', subCategory: 'SWAMP', catId: 'AMBSwmp' },
  { category: 'AMBIENCE', subCategory: 'TOWN', catId: 'AMBTown' },
  { category: 'AMBIENCE', subCategory: 'TRAFFIC', catId: 'AMBTraf' },
  { category: 'AMBIENCE', subCategory: 'TRANSPORTATION', catId: 'AMBTran' },
  { category: 'AMBIENCE', subCategory: 'TROPICAL', catId: 'AMBTrop' },
  { category: 'AMBIENCE', subCategory: 'TUNDRA', catId: 'AMBTndra' },
  { category: 'AMBIENCE', subCategory: 'UNDERGROUND', catId: 'AMBUndr' },
  { category: 'AMBIENCE', subCategory: 'UNDERWATER', catId: 'AMBUndwtr' },
  { category: 'AMBIENCE', subCategory: 'URBAN', catId: 'AMBUrbn' },
  { category: 'AMBIENCE', subCategory: 'WARFARE', catId: 'AMBWar' },
  { category: 'ANIMALS', subCategory: 'AMPHIBIAN', catId: 'ANMLAmph' },
  { category: 'ANIMALS', subCategory: 'AQUATIC', catId: 'ANMLAqua' },
  { category: 'ANIMALS', subCategory: 'BAT', catId: 'ANMLBat' },
  { category: 'ANIMALS', subCategory: 'CAT DOMESTIC', catId: 'ANMLCat' },
  { category: 'ANIMALS', subCategory: 'CAT WILD', catId: 'ANMLWcat' },
  { category: 'ANIMALS', subCategory: 'DOG', catId: 'ANMLDog' },
  { category: 'ANIMALS', subCategory: 'DOG WILD', catId: 'ANMLWdog' },
  { category: 'ANIMALS', subCategory: 'FARM', catId: 'ANMLFarm' },
  { category: 'ANIMALS', subCategory: 'HORSE', catId: 'ANMLHors' },
  { category: 'ANIMALS', subCategory: 'INSECT', catId: 'ANMLInsc' },
  { category: 'ANIMALS', subCategory: 'MISC', catId: 'ANMLMisc' },
  { category: 'ANIMALS', subCategory: 'PRIMATE', catId: 'ANMLPrim' },
  { category: 'ANIMALS', subCategory: 'REPTILE', catId: 'ANMLRept' },
  { category: 'ANIMALS', subCategory: 'RODENT', catId: 'ANMLRdnt' },
  { category: 'ANIMALS', subCategory: 'WILD', catId: 'ANMLWild' },
  { category: 'ARCHIVED', subCategory: 'ADR', catId: 'ADR' },
  { category: 'ARCHIVED', subCategory: 'ASSET', catId: 'ASSET' },
  { category: 'ARCHIVED', subCategory: 'BOUNCE', catId: 'BNCE' },
  { category: 'ARCHIVED', subCategory: 'IMPULSE RESPONSE', catId: 'IR' },
  { category: 'ARCHIVED', subCategory: 'LOOP GROUP', catId: 'LPGRP' },
  { category: 'ARCHIVED', subCategory: 'MIX', catId: 'MIX' },
  { category: 'ARCHIVED', subCategory: 'PFX', catId: 'PFX' },
  { category: 'ARCHIVED', subCategory: 'PRODUCTION', catId: 'PROD' },
  { category: 'ARCHIVED', subCategory: 'RAW', catId: 'RAW' },
  { category: 'ARCHIVED', subCategory: 'REFERENCE', catId: 'REF' },
  { category: 'ARCHIVED', subCategory: 'SCENE', catId: 'SCNE' },
  { category: 'ARCHIVED', subCategory: 'TEST TONE', catId: 'TEST' },
  { category: 'ARCHIVED', subCategory: 'TRADEMARKED', catId: 'TMARK' },
  { category: 'ARCHIVED', subCategory: 'WORK IN PROGRESS', catId: 'WIP' },
  { category: 'ARCHIVED', subCategory: 'WTF', catId: 'WTF' },
  { category: 'BEEPS', subCategory: 'APPLIANCE', catId: 'BEEPAppl' },
  { category: 'BEEPS', subCategory: 'GENERAL', catId: 'BEEP' },
  { category: 'BEEPS', subCategory: 'LOFI', catId: 'BEEPLofi' },
  { category: 'BEEPS', subCategory: 'MEDICAL', catId: 'BEEPMed' },
  { category: 'BEEPS', subCategory: 'TIMER', catId: 'BEEPTimer' },
  { category: 'BEEPS', subCategory: 'VEHICLE', catId: 'BEEPVeh' },
  { category: 'BELLS', subCategory: 'ANIMAL', catId: 'BELLAnml' },
  { category: 'BELLS', subCategory: 'DOORBELL', catId: 'BELLDoor' },
  { category: 'BELLS', subCategory: 'GONG', catId: 'BELLGong' },
  { category: 'BELLS', subCategory: 'HANDBELL', catId: 'BELLHand' },
  { category: 'BELLS', subCategory: 'LARGE', catId: 'BELLLrg' },
  { category: 'BELLS', subCategory: 'MISC', catId: 'BELLMisc' },
  { category: 'BIRDS', subCategory: 'BIRD OF PREY', catId: 'BIRDPrey' },
  { category: 'BIRDS', subCategory: 'CROW', catId: 'BIRDCrow' },
  { category: 'BIRDS', subCategory: 'FOWL', catId: 'BIRDFowl' },
  { category: 'BIRDS', subCategory: 'MISC', catId: 'BIRDMisc' },
  { category: 'BIRDS', subCategory: 'SEA', catId: 'BIRDSea' },
  { category: 'BIRDS', subCategory: 'SONGBIRD', catId: 'BIRDSong' },
  { category: 'BIRDS', subCategory: 'TROPICAL', catId: 'BIRDTrop' },
  { category: 'BIRDS', subCategory: 'WADING', catId: 'BIRDWade' },
  { category: 'BOATS', subCategory: 'AIR BOAT', catId: 'BOATAir' },
  { category: 'BOATS', subCategory: 'BOW WASH', catId: 'BOATWash' },
  { category: 'BOATS', subCategory: 'DOOR', catId: 'BOATDoor' },
  { category: 'BOATS', subCategory: 'ELECTRIC', catId: 'BOATElec' },
  { category: 'BOATS', subCategory: 'FISHING', catId: 'BOATFish' },
  { category: 'BOATS', subCategory: 'HORN', catId: 'BOATHorn' },
  { category: 'BOATS', subCategory: 'INTERIOR', catId: 'BOATInt' },
  { category: 'BOATS', subCategory: 'MECHANISM', catId: 'BOATMech' },
  { category: 'BOATS', subCategory: 'MILITARY', catId: 'BOATMil' },
  { category: 'BOATS', subCategory: 'MISC', catId: 'BOATMisc' },
  { category: 'BOATS', subCategory: 'MOTORBOAT', catId: 'BOATMotr' },
  { category: 'BOATS', subCategory: 'RACING', catId: 'BOATRace' },
  { category: 'BOATS', subCategory: 'ROWBOAT', catId: 'BOATRow' },
  { category: 'BOATS', subCategory: 'SAILBOAT', catId: 'BOATSail' },
  { category: 'BOATS', subCategory: 'SHIP', catId: 'BOATShip' },
  { category: 'BOATS', subCategory: 'STEAM', catId: 'BOATStm' },
  { category: 'BOATS', subCategory: 'SUBMARINE', catId: 'BOATSub' },
  { category: 'BOATS', subCategory: 'UNDERWATER', catId: 'BOATUndwtr' },
  { category: 'BULLETS', subCategory: 'BY', catId: 'BLLTBy' },
  { category: 'BULLETS', subCategory: 'IMPACT', catId: 'BLLTImpt' },
  { category: 'BULLETS', subCategory: 'MISC', catId: 'BLLTMisc' },
  { category: 'BULLETS', subCategory: 'RICOCHET', catId: 'BLLTRico' },
  { category: 'BULLETS', subCategory: 'SHELL', catId: 'BLLTShel' },
  { category: 'CARTOON', subCategory: 'ANIMAL', catId: 'TOONAnml' },
  { category: 'CARTOON', subCategory: 'BOING', catId: 'TOONBoing' },
  { category: 'CARTOON', subCategory: 'CLANG', catId: 'TOONClang' },
  { category: 'CARTOON', subCategory: 'CREAK', catId: 'TOONCreak' },
  { category: 'CARTOON', subCategory: 'HORN', catId: 'TOONHorn' },
  { category: 'CARTOON', subCategory: 'IMPACT', catId: 'TOONImpt' },
  { category: 'CARTOON', subCategory: 'MACHINE', catId: 'TOONMach' },
  { category: 'CARTOON', subCategory: 'MISC', catId: 'TOONMisc' },
  { category: 'CARTOON', subCategory: 'MUSICAL', catId: 'TOONMx' },
  { category: 'CARTOON', subCategory: 'PLUCK', catId: 'TOONPluk' },
  { category: 'CARTOON', subCategory: 'POP', catId: 'TOONPop' },
  { category: 'CARTOON', subCategory: 'SHAKE', catId: 'TOONShake' },
  { category: 'CARTOON', subCategory: 'SPLAT', catId: 'TOONSplt' },
  { category: 'CARTOON', subCategory: 'SQUEAK', catId: 'TOONSqk' },
  { category: 'CARTOON', subCategory: 'STRETCH', catId: 'TOONStrch' },
  { category: 'CARTOON', subCategory: 'SWISH', catId: 'TOONSwsh' },
  { category: 'CARTOON', subCategory: 'TWANG', catId: 'TOONTwang' },
  { category: 'CARTOON', subCategory: 'VEHICLE', catId: 'TOONVeh' },
  { category: 'CARTOON', subCategory: 'VOCAL', catId: 'TOONVox' },
  { category: 'CARTOON', subCategory: 'WARBLE', catId: 'TOONWarb' },
  { category: 'CARTOON', subCategory: 'WHISTLE', catId: 'TOONWhis' },
  { category: 'CARTOON', subCategory: 'ZIP', catId: 'TOONZip' },
  { category: 'CERAMICS', subCategory: 'BREAK', catId: 'CERMBrk' },
  { category: 'CERAMICS', subCategory: 'CRASH & DEBRIS', catId: 'CERMCrsh' },
  { category: 'CERAMICS', subCategory: 'FRICTION', catId: 'CERMFric' },
  { category: 'CERAMICS', subCategory: 'HANDLE', catId: 'CERMHndl' },
  { category: 'CERAMICS', subCategory: 'IMPACT', catId: 'CERMImpt' },
  { category: 'CERAMICS', subCategory: 'MISC', catId: 'CERMMisc' },
  { category: 'CERAMICS', subCategory: 'MOVEMENT', catId: 'CERMMvmt' },
  { category: 'CERAMICS', subCategory: 'TONAL', catId: 'CERMTonl' },
  { category: 'CHAINS', subCategory: 'BREAK', catId: 'CHAINBrk' },
  { category: 'CHAINS', subCategory: 'HANDLE', catId: 'CHAINHndl' },
  { category: 'CHAINS', subCategory: 'IMPACT', catId: 'CHAINImpt' },
  { category: 'CHAINS', subCategory: 'MISC', catId: 'CHAINMisc' },
  { category: 'CHAINS', subCategory: 'MOVEMENT', catId: 'CHAINMvmt' },
  { category: 'CHEMICALS', subCategory: 'ACID', catId: 'CHEMAcid' },
  { category: 'CHEMICALS', subCategory: 'MISC', catId: 'CHEMMisc' },
  { category: 'CHEMICALS', subCategory: 'REACTION', catId: 'CHEMReac' },
  { category: 'CLOCKS', subCategory: 'CHIME', catId: 'CLOCKChim' },
  { category: 'CLOCKS', subCategory: 'MECHANICS', catId: 'CLOCKMech' },
  { category: 'CLOCKS', subCategory: 'MISC', catId: 'CLOCKMisc' },
  { category: 'CLOCKS', subCategory: 'TICK', catId: 'CLOCKTick' },
  { category: 'CLOTH', subCategory: 'FLAP', catId: 'CLOTHFlp' },
  { category: 'CLOTH', subCategory: 'HANDLE', catId: 'CLOTHHndl' },
  { category: 'CLOTH', subCategory: 'IMPACT', catId: 'CLOTHImpt' },
  { category: 'CLOTH', subCategory: 'MISC', catId: 'CLOTHMisc' },
  { category: 'CLOTH', subCategory: 'MOVEMENT', catId: 'CLOTHMvmt' },
  { category: 'CLOTH', subCategory: 'RIP', catId: 'CLOTHRip' },
  { category: 'COMMUNICATIONS', subCategory: 'AUDIO VISUAL', catId: 'COMAv' },
  { category: 'COMMUNICATIONS', subCategory: 'CAMERA', catId: 'COMCam' },
  { category: 'COMMUNICATIONS', subCategory: 'CELLPHONE', catId: 'COMCell' },
  { category: 'COMMUNICATIONS', subCategory: 'MICROPHONE', catId: 'COMMic' },
  { category: 'COMMUNICATIONS', subCategory: 'MISC', catId: 'COMMisc' },
  { category: 'COMMUNICATIONS', subCategory: 'PHONOGRAPH', catId: 'COMPhono' },
  { category: 'COMMUNICATIONS', subCategory: 'RADIO', catId: 'COMRadio' },
  { category: 'COMMUNICATIONS', subCategory: 'STATIC', catId: 'COMStatic' },
  { category: 'COMMUNICATIONS', subCategory: 'TELEMETRY', catId: 'COMTelm' },
  { category: 'COMMUNICATIONS', subCategory: 'TELEPHONE', catId: 'COMTelph' },
  { category: 'COMMUNICATIONS', subCategory: 'TELEVISION', catId: 'COMTv' },
  { category: 'COMMUNICATIONS', subCategory: 'TRANSCEIVER', catId: 'COMTran' },
  { category: 'COMMUNICATIONS', subCategory: 'TYPEWRITER', catId: 'COMType' },
  { category: 'COMPUTERS', subCategory: 'HARD DRIVE', catId: 'CMPTDriv' },
  { category: 'COMPUTERS', subCategory: 'KEYBOARD & MOUSE', catId: 'CMPTKey' },
  { category: 'COMPUTERS', subCategory: 'MISC', catId: 'CMPTMisc' },
  { category: 'CREATURES', subCategory: 'AQUATIC', catId: 'CREAAqua' },
  { category: 'CREATURES', subCategory: 'AVIAN', catId: 'CREAAvian' },
  { category: 'CREATURES', subCategory: 'BEAST', catId: 'CREABeast' },
  { category: 'CREATURES', subCategory: 'BLOB', catId: 'CREABlob' },
  { category: 'CREATURES', subCategory: 'DINOSAUR', catId: 'CREADino' },
  { category: 'CREATURES', subCategory: 'DRAGON', catId: 'CREADrgn' },
  { category: 'CREATURES', subCategory: 'ELEMENTAL', catId: 'CREAElem' },
  { category: 'CREATURES', subCategory: 'ETHEREAL', catId: 'CREAEthr' },
  { category: 'CREATURES', subCategory: 'HUMANOID', catId: 'CREAHmn' },
  { category: 'CREATURES', subCategory: 'INSECTOID', catId: 'CREAInsc' },
  { category: 'CREATURES', subCategory: 'MISC', catId: 'CREAMisc' },
  { category: 'CREATURES', subCategory: 'MONSTER', catId: 'CREAMnstr' },
  { category: 'CREATURES', subCategory: 'REPTILIAN', catId: 'CREARept' },
  { category: 'CREATURES', subCategory: 'SMALL', catId: 'CREASmall' },
  { category: 'CREATURES', subCategory: 'SOURCE', catId: 'CREASrce' },
  { category: 'CROWDS', subCategory: 'ANGRY', catId: 'CRWDAngr' },
  { category: 'CROWDS', subCategory: 'APPLAUSE', catId: 'CRWDApls' },
  { category: 'CROWDS', subCategory: 'BATTLE', catId: 'CRWDBatl' },
  { category: 'CROWDS', subCategory: 'CELEBRATION', catId: 'CRWDCele' },
  { category: 'CROWDS', subCategory: 'CHEERING', catId: 'CRWDCheer' },
  { category: 'CROWDS', subCategory: 'CHILDREN', catId: 'CRWDChld' },
  { category: 'CROWDS', subCategory: 'CONVERSATION', catId: 'CRWDConv' },
  { category: 'CROWDS', subCategory: 'LAUGHTER', catId: 'CRWDLaff' },
  { category: 'CROWDS', subCategory: 'LOOP GROUP', catId: 'CRWDLoop' },
  { category: 'CROWDS', subCategory: 'MISC', catId: 'CRWDMisc' },
  { category: 'CROWDS', subCategory: 'PANIC', catId: 'CRWDPanic' },
  { category: 'CROWDS', subCategory: 'QUIET', catId: 'CRWDQuiet' },
  { category: 'CROWDS', subCategory: 'REACTION', catId: 'CRWDReac' },
  { category: 'CROWDS', subCategory: 'SINGING', catId: 'CRWDSing' },
  { category: 'CROWDS', subCategory: 'SPORT', catId: 'CRWDSprt' },
  { category: 'CROWDS', subCategory: 'WALLA', catId: 'CRWDWalla' },
  { category: 'DESIGNED', subCategory: 'BASS DIVE', catId: 'DSGNBass' },
  { category: 'DESIGNED', subCategory: 'BOOM', catId: 'DSGNBoom' },
  { category: 'DESIGNED', subCategory: 'BRAAM', catId: 'DSGNBram' },
  { category: 'DESIGNED', subCategory: 'DISTORTION', catId: 'DSGNDist' },
  { category: 'DESIGNED', subCategory: 'DRONE', catId: 'DSGNDron' },
  { category: 'DESIGNED', subCategory: 'EERIE', catId: 'DSGNErie' },
  { category: 'DESIGNED', subCategory: 'ETHEREAL', catId: 'DSGNEthr' },
  { category: 'DESIGNED', subCategory: 'GRANULAR', catId: 'DSGNGran' },
  { category: 'DESIGNED', subCategory: 'IMPACT', catId: 'DSGNImpt' },
  { category: 'DESIGNED', subCategory: 'MISC', catId: 'DSGNMisc' },
  { category: 'DESIGNED', subCategory: 'MORPH', catId: 'DSGNMorph' },
  { category: 'DESIGNED', subCategory: 'RISER', catId: 'DSGNRise' },
  { category: 'DESIGNED', subCategory: 'RUMBLE', catId: 'DSGNRmbl' },
  { category: 'DESIGNED', subCategory: 'RHYTHMIC', catId: 'DSGNRythm' },
  { category: 'DESIGNED', subCategory: 'SOURCE', catId: 'DSGNSrce' },
  { category: 'DESIGNED', subCategory: 'STINGER', catId: 'DSGNStngr' },
  { category: 'DESIGNED', subCategory: 'SYNTHETIC', catId: 'DSGNSynth' },
  { category: 'DESIGNED', subCategory: 'TONAL', catId: 'DSGNTonl' },
  { category: 'DESIGNED', subCategory: 'VOCAL', catId: 'DSGNVocl' },
  { category: 'DESIGNED', subCategory: 'WHOOSH', catId: 'DSGNWhsh' },
  { category: 'DESTRUCTION', subCategory: 'COLLAPSE', catId: 'DESTRClpse' },
  { category: 'DESTRUCTION', subCategory: 'CRASH & DEBRIS', catId: 'DESTRCrsh' },
  { category: 'DESTRUCTION', subCategory: 'MISC', catId: 'DESTRMisc' },
  { category: 'DIRT & SAND', subCategory: 'CRASH & DEBRIS', catId: 'DIRTCrsh' },
  { category: 'DIRT & SAND', subCategory: 'DUST', catId: 'DIRTDust' },
  { category: 'DIRT & SAND', subCategory: 'HANDLE', catId: 'DIRTHndl' },
  { category: 'DIRT & SAND', subCategory: 'IMPACT', catId: 'DIRTImpt' },
  { category: 'DIRT & SAND', subCategory: 'MISC', catId: 'DIRTMisc' },
  { category: 'DIRT & SAND', subCategory: 'MOVEMENT', catId: 'DIRTMvmt' },
  { category: 'DIRT & SAND', subCategory: 'TONAL', catId: 'DIRTTonl' },
  { category: 'DOORS', subCategory: 'ANTIQUE', catId: 'DOORAntq' },
  { category: 'DOORS', subCategory: 'APPLIANCE', catId: 'DOORAppl' },
  { category: 'DOORS', subCategory: 'CABINET', catId: 'DOORCab' },
  { category: 'DOORS', subCategory: 'COMPOSITE', catId: 'DOORComp' },
  { category: 'DOORS', subCategory: 'CREAK', catId: 'DOORCreak' },
  { category: 'DOORS', subCategory: 'DUNGEON', catId: 'DOORDungn' },
  { category: 'DOORS', subCategory: 'ELECTRIC', catId: 'DOORElec' },
  { category: 'DOORS', subCategory: 'GATE', catId: 'DOORGate' },
  { category: 'DOORS', subCategory: 'GLASS', catId: 'DOORGlas' },
  { category: 'DOORS', subCategory: 'HARDWARE', catId: 'DOORHdwr' },
  { category: 'DOORS', subCategory: 'HITECH', catId: 'DOORTech' },
  { category: 'DOORS', subCategory: 'HYDRAULIC & PNEUMATIC', catId: 'DOORHydr' },
  { category: 'DOORS', subCategory: 'KNOCK', catId: 'DOORKnck' },
  { category: 'DOORS', subCategory: 'METAL', catId: 'DOORMetl' },
  { category: 'DOORS', subCategory: 'MISC', catId: 'DOORMisc' },
  { category: 'DOORS', subCategory: 'PLASTIC', catId: 'DOORPlas' },
  { category: 'DOORS', subCategory: 'PRISON', catId: 'DOORPrisn' },
  { category: 'DOORS', subCategory: 'REVOLVING', catId: 'DOORRevl' },
  { category: 'DOORS', subCategory: 'SLIDING', catId: 'DOORSlid' },
  { category: 'DOORS', subCategory: 'STONE', catId: 'DOORSton' },
  { category: 'DOORS', subCategory: 'SWINGING', catId: 'DOORSwng' },
  { category: 'DOORS', subCategory: 'WOOD', catId: 'DOORWood' },
  { category: 'DRAWERS', subCategory: 'METAL', catId: 'DRWRMetl' },
  { category: 'DRAWERS', subCategory: 'MISC', catId: 'DRWRMisc' },
  { category: 'DRAWERS', subCategory: 'PLASTIC', catId: 'DRWRPlas' },
  { category: 'DRAWERS', subCategory: 'WOOD', catId: 'DRWRWood' },
  { category: 'ELECTRICITY', subCategory: 'ARC', catId: 'ELECArc' },
  { category: 'ELECTRICITY', subCategory: 'BUZZ & HUM', catId: 'ELECBuzz' },
  { category: 'ELECTRICITY', subCategory: 'ELECTROMAGNETIC', catId: 'ELECEmf' },
  { category: 'ELECTRICITY', subCategory: 'MISC', catId: 'ELECMisc' },
  { category: 'ELECTRICITY', subCategory: 'SPARKS', catId: 'ELECSprk' },
  { category: 'ELECTRICITY', subCategory: 'ZAP', catId: 'ELECZap' },
  { category: 'EQUIPMENT', subCategory: 'BRIDLE & TACK', catId: 'EQUIPBridle' },
  { category: 'EQUIPMENT', subCategory: 'HITECH', catId: 'EQUIPTech' },
  { category: 'EQUIPMENT', subCategory: 'MISC', catId: 'EQUIPMisc' },
  { category: 'EQUIPMENT', subCategory: 'RECREATIONAL', catId: 'EQUIPRec' },
  { category: 'EQUIPMENT', subCategory: 'SPORT', catId: 'EQUIPSprt' },
  { category: 'EQUIPMENT', subCategory: 'TACTICAL', catId: 'EQUIPTact' },
  { category: 'EXPLOSIONS', subCategory: 'DESIGNED', catId: 'EXPLDsgn' },
  { category: 'EXPLOSIONS', subCategory: 'MISC', catId: 'EXPLMisc' },
  { category: 'EXPLOSIONS', subCategory: 'REAL', catId: 'EXPLReal' },
  { category: 'FARTS', subCategory: 'DESIGNED', catId: 'FARTDsgn' },
  { category: 'FARTS', subCategory: 'MISC', catId: 'FARTMisc' },
  { category: 'FARTS', subCategory: 'REAL', catId: 'FARTReal' },
  { category: 'FIGHT', subCategory: 'BODYFALL', catId: 'FGHTBf' },
  { category: 'FIGHT', subCategory: 'CLOTH', catId: 'FGHTClth' },
  { category: 'FIGHT', subCategory: 'GRAB', catId: 'FGHTGrab' },
  { category: 'FIGHT', subCategory: 'IMPACT', catId: 'FGHTImpt' },
  { category: 'FIGHT', subCategory: 'MISC', catId: 'FGHTMisc' },
  { category: 'FIRE', subCategory: 'BURNING', catId: 'FIREBurn' },
  { category: 'FIRE', subCategory: 'BURST', catId: 'FIREBrst' },
  { category: 'FIRE', subCategory: 'CRACKLE', catId: 'FIRECrkl' },
  { category: 'FIRE', subCategory: 'GAS', catId: 'FIREGas' },
  { category: 'FIRE', subCategory: 'IGNITE', catId: 'FIREIgn' },
  { category: 'FIRE', subCategory: 'MISC', catId: 'FIREMisc' },
  { category: 'FIRE', subCategory: 'SIZZLE', catId: 'FIRESizz' },
  { category: 'FIRE', subCategory: 'TORCH', catId: 'FIRETrch' },
  { category: 'FIRE', subCategory: 'TURBULENT', catId: 'FIRETurb' },
  { category: 'FIRE', subCategory: 'WHOOSH', catId: 'FIREWhsh' },
  { category: 'FIREWORKS', subCategory: 'COMMERCIAL', catId: 'FRWKComr' },
  { category: 'FIREWORKS', subCategory: 'MISC', catId: 'FRWKMisc' },
  { category: 'FIREWORKS', subCategory: 'RECREATIONAL', catId: 'FRWKRec' },
  { category: 'FOLEY', subCategory: 'CLOTH', catId: 'FOLYClth' },
  { category: 'FOLEY', subCategory: 'FEET', catId: 'FOLYFeet' },
  { category: 'FOLEY', subCategory: 'HANDS', catId: 'FOLYHand' },
  { category: 'FOLEY', subCategory: 'MISC', catId: 'FOLYMisc' },
  { category: 'FOLEY', subCategory: 'PROP', catId: 'FOLYProp' },
  { category: 'FOOD & DRINK', subCategory: 'COOKING', catId: 'FOODCook' },
  { category: 'FOOD & DRINK', subCategory: 'DRINKING', catId: 'FOODDrnk' },
  { category: 'FOOD & DRINK', subCategory: 'EATING', catId: 'FOODEat' },
  { category: 'FOOD & DRINK', subCategory: 'GLASSWARE', catId: 'FOODGware' },
  { category: 'FOOD & DRINK', subCategory: 'INGREDIENTS', catId: 'FOODIngr' },
  { category: 'FOOD & DRINK', subCategory: 'KITCHENWARE', catId: 'FOODKware' },
  { category: 'FOOD & DRINK', subCategory: 'MISC', catId: 'FOODMisc' },
  { category: 'FOOD & DRINK', subCategory: 'POUR', catId: 'FOODPour' },
  { category: 'FOOD & DRINK', subCategory: 'TABLEWARE', catId: 'FOODTware' },
  { category: 'FOOTSTEPS', subCategory: 'ANIMAL', catId: 'FEETAnml' },
  { category: 'FOOTSTEPS', subCategory: 'CREATURE', catId: 'FEETCrea' },
  { category: 'FOOTSTEPS', subCategory: 'HORSE', catId: 'FEETHors' },
  { category: 'FOOTSTEPS', subCategory: 'HUMAN', catId: 'FEETHmn' },
  { category: 'FOOTSTEPS', subCategory: 'MISC', catId: 'FEETMisc' },
  { category: 'GAMES', subCategory: 'ARCADE', catId: 'GAMEArcd' },
  { category: 'GAMES', subCategory: 'BOARD', catId: 'GAMEBoard' },
  { category: 'GAMES', subCategory: 'CASINO', catId: 'GAMECas' },
  { category: 'GAMES', subCategory: 'MISC', catId: 'GAMEMisc' },
  { category: 'GAMES', subCategory: 'VIDEO', catId: 'GAMEVideo' },
  { category: 'GEOTHERMAL', subCategory: 'FUMAROLE', catId: 'GEOFuma' },
  { category: 'GEOTHERMAL', subCategory: 'GEYSER', catId: 'GEOGeyser' },
  { category: 'GEOTHERMAL', subCategory: 'LAVA', catId: 'GEOLava' },
  { category: 'GEOTHERMAL', subCategory: 'MISC', catId: 'GEOMisc' },
  { category: 'GEOTHERMAL', subCategory: 'MUD POTS', catId: 'GEOMudpot' },
  { category: 'GLASS', subCategory: 'BREAK', catId: 'GLASBrk' },
  { category: 'GLASS', subCategory: 'CRASH & DEBRIS', catId: 'GLASCrsh' },
  { category: 'GLASS', subCategory: 'FRICTION', catId: 'GLASFric' },
  { category: 'GLASS', subCategory: 'HANDLE', catId: 'GLASHndl' },
  { category: 'GLASS', subCategory: 'IMPACT', catId: 'GLASImpt' },
  { category: 'GLASS', subCategory: 'MISC', catId: 'GLASMisc' },
  { category: 'GLASS', subCategory: 'MOVEMENT', catId: 'GLASMvmt' },
  { category: 'GLASS', subCategory: 'TONAL', catId: 'GLASTonl' },
  { category: 'GORE', subCategory: 'BLOOD', catId: 'GOREBlood' },
  { category: 'GORE', subCategory: 'BONE', catId: 'GOREBone' },
  { category: 'GORE', subCategory: 'BURN', catId: 'GOREBurn' },
  { category: 'GORE', subCategory: 'FLESH', catId: 'GOREFlsh' },
  { category: 'GORE', subCategory: 'MISC', catId: 'GOREMisc' },
  { category: 'GORE', subCategory: 'OOZE', catId: 'GOREOoze' },
  { category: 'GORE', subCategory: 'SOURCE', catId: 'GORESrce' },
  { category: 'GORE', subCategory: 'SPLAT', catId: 'GORESplt' },
  { category: 'GORE', subCategory: 'SQUISH', catId: 'GORESqsh' },
  { category: 'GORE', subCategory: 'STAB', catId: 'GOREStab' },
  { category: 'GUNS', subCategory: 'ANTIQUE', catId: 'GUNAntq' },
  { category: 'GUNS', subCategory: 'ARTILLERY', catId: 'GUNArtl' },
  { category: 'GUNS', subCategory: 'AUTOMATIC', catId: 'GUNAuto' },
  { category: 'GUNS', subCategory: 'CANNON', catId: 'GUNCano' },
  { category: 'GUNS', subCategory: 'HANDLE', catId: 'GUNHndl' },
  { category: 'GUNS', subCategory: 'HITECH', catId: 'GUNTech' },
  { category: 'GUNS', subCategory: 'MECHANISM', catId: 'GUNMech' },
  { category: 'GUNS', subCategory: 'MISC', catId: 'GUNMisc' },
  { category: 'GUNS', subCategory: 'PISTOL', catId: 'GUNPis' },
  { category: 'GUNS', subCategory: 'RIFLE', catId: 'GUNRif' },
  { category: 'GUNS', subCategory: 'SHOTGUN', catId: 'GUNShotg' },
  { category: 'GUNS', subCategory: 'SUPPRESSED', catId: 'GUNSupr' },
  { category: 'HORNS', subCategory: 'AIR POWERED', catId: 'HORNAir' },
  { category: 'HORNS', subCategory: 'CELEBRATION', catId: 'HORNCele' },
  { category: 'HORNS', subCategory: 'MISC', catId: 'HORNMisc' },
  { category: 'HORNS', subCategory: 'TRADITIONAL', catId: 'HORNTrad' },
  { category: 'HUMAN', subCategory: 'BLOW', catId: 'HMNBlow' },
  { category: 'HUMAN', subCategory: 'BREATH', catId: 'HMNBrth' },
  { category: 'HUMAN', subCategory: 'BURP', catId: 'HMNBurp' },
  { category: 'HUMAN', subCategory: 'COUGH', catId: 'HMNCough' },
  { category: 'HUMAN', subCategory: 'HEARTBEAT', catId: 'HMNHart' },
  { category: 'HUMAN', subCategory: 'KISS', catId: 'HMNKiss' },
  { category: 'HUMAN', subCategory: 'MISC', catId: 'HMNMisc' },
  { category: 'HUMAN', subCategory: 'PEE', catId: 'HMNPee' },
  { category: 'HUMAN', subCategory: 'SKIN', catId: 'HMNSkin' },
  { category: 'HUMAN', subCategory: 'SNEEZE', catId: 'HMNSneez' },
  { category: 'HUMAN', subCategory: 'SNIFF', catId: 'HMNSniff' },
  { category: 'HUMAN', subCategory: 'SNORE', catId: 'HMNSnor' },
  { category: 'HUMAN', subCategory: 'SPIT', catId: 'HMNSpit' },
  { category: 'HUMAN', subCategory: 'VOMIT', catId: 'HMNVomit' },
  { category: 'ICE', subCategory: 'BREAK', catId: 'ICEBrk' },
  { category: 'ICE', subCategory: 'CRASH & DEBRIS', catId: 'ICECrsh' },
  { category: 'ICE', subCategory: 'FRICTION', catId: 'ICEFric' },
  { category: 'ICE', subCategory: 'HANDLE', catId: 'ICEHndl' },
  { category: 'ICE', subCategory: 'IMPACT', catId: 'ICEImpt' },
  { category: 'ICE', subCategory: 'MISC', catId: 'ICEMisc' },
  { category: 'ICE', subCategory: 'MOVEMENT', catId: 'ICEMvmt' },
  { category: 'ICE', subCategory: 'TONAL', catId: 'ICETonl' },
  { category: 'LASERS', subCategory: 'BEAM', catId: 'LASRBeam' },
  { category: 'LASERS', subCategory: 'GUN', catId: 'LASRGun' },
  { category: 'LASERS', subCategory: 'IMPACT', catId: 'LASRImpt' },
  { category: 'LASERS', subCategory: 'MISC', catId: 'LASRMisc' },
  { category: 'LEATHER', subCategory: 'CREAK', catId: 'LETHRCreak' },
  { category: 'LEATHER', subCategory: 'HANDLE', catId: 'LETHRHndl' },
  { category: 'LEATHER', subCategory: 'IMPACT', catId: 'LETHRImpt' },
  { category: 'LEATHER', subCategory: 'MISC', catId: 'LETHRMisc' },
  { category: 'LEATHER', subCategory: 'MOVEMENT', catId: 'LETHRMvmt' },
  { category: 'LIQUID & MUD', subCategory: 'BUBBLES', catId: 'LIQBubl' },
  { category: 'LIQUID & MUD', subCategory: 'IMPACT', catId: 'LIQImpt' },
  { category: 'LIQUID & MUD', subCategory: 'MISC', catId: 'LIQMisc' },
  { category: 'LIQUID & MUD', subCategory: 'MOVEMENT', catId: 'LIQMvmt' },
  { category: 'LIQUID & MUD', subCategory: 'SUCTION', catId: 'LIQSuct' },
  { category: 'MACHINES', subCategory: 'AMUSEMENT', catId: 'MACHAmus' },
  { category: 'MACHINES', subCategory: 'ANTIQUE', catId: 'MACHAntq' },
  { category: 'MACHINES', subCategory: 'APPLIANCE', catId: 'MACHAppl' },
  { category: 'MACHINES', subCategory: 'CONSTRUCTION', catId: 'MACHCnst' },
  { category: 'MACHINES', subCategory: 'ELEVATOR', catId: 'MACHElev' },
  { category: 'MACHINES', subCategory: 'ESCALATOR', catId: 'MACHEscl' },
  { category: 'MACHINES', subCategory: 'FAN', catId: 'MACHFan' },
  { category: 'MACHINES', subCategory: 'GARDEN', catId: 'MACHGrdn' },
  { category: 'MACHINES', subCategory: 'GYM', catId: 'MACHGym' },
  { category: 'MACHINES', subCategory: 'HITECH', catId: 'MACHTech' },
  { category: 'MACHINES', subCategory: 'HVAC', catId: 'MACHHvac' },
  { category: 'MACHINES', subCategory: 'INDUSTRIAL', catId: 'MACHInd' },
  { category: 'MACHINES', subCategory: 'MECHANISM', catId: 'MACHMech' },
  { category: 'MACHINES', subCategory: 'MEDICAL', catId: 'MACHMed' },
  { category: 'MACHINES', subCategory: 'MISC', catId: 'MACHMisc' },
  { category: 'MACHINES', subCategory: 'OFFICE', catId: 'MACHOffc' },
  { category: 'MACHINES', subCategory: 'PUMP', catId: 'MACHPump' },
  { category: 'MAGIC', subCategory: 'ANGELIC', catId: 'MAGAngl' },
  { category: 'MAGIC', subCategory: 'ELEMENTAL', catId: 'MAGElem' },
  { category: 'MAGIC', subCategory: 'EVIL', catId: 'MAGEvil' },
  { category: 'MAGIC', subCategory: 'MISC', catId: 'MAGMisc' },
  { category: 'MAGIC', subCategory: 'POOF', catId: 'MAGPoof' },
  { category: 'MAGIC', subCategory: 'SHIMMER', catId: 'MAGShim' },
  { category: 'MAGIC', subCategory: 'SPELL', catId: 'MAGSpel' },
  { category: 'MECHANICAL', subCategory: 'CLICK', catId: 'MECHClik' },
  { category: 'MECHANICAL', subCategory: 'GEARS', catId: 'MECHGear' },
  { category: 'MECHANICAL', subCategory: 'HYDRAULIC & PNEUMATIC', catId: 'MECHHydr' },
  { category: 'MECHANICAL', subCategory: 'LATCH', catId: 'MECHLtch' },
  { category: 'MECHANICAL', subCategory: 'LEVER', catId: 'MECHLvr' },
  { category: 'MECHANICAL', subCategory: 'LOCK', catId: 'MECHLock' },
  { category: 'MECHANICAL', subCategory: 'MISC', catId: 'MECHMisc' },
  { category: 'MECHANICAL', subCategory: 'PULLEY', catId: 'MECHPuly' },
  { category: 'MECHANICAL', subCategory: 'RATCHET', catId: 'MECHRtch' },
  { category: 'MECHANICAL', subCategory: 'RELAY', catId: 'MECHRelay' },
  { category: 'MECHANICAL', subCategory: 'ROLLER', catId: 'MECHRolr' },
  { category: 'MECHANICAL', subCategory: 'SWITCH', catId: 'MECHSwtch' },
  { category: 'METAL', subCategory: 'BREAK', catId: 'METLBrk' },
  { category: 'METAL', subCategory: 'CRASH & DEBRIS', catId: 'METLCrsh' },
  { category: 'METAL', subCategory: 'FRICTION', catId: 'METLFric' },
  { category: 'METAL', subCategory: 'HANDLE', catId: 'METLHndl' },
  { category: 'METAL', subCategory: 'IMPACT', catId: 'METLImpt' },
  { category: 'METAL', subCategory: 'MISC', catId: 'METLMisc' },
  { category: 'METAL', subCategory: 'MOVEMENT', catId: 'METLMvmt' },
  { category: 'METAL', subCategory: 'TONAL', catId: 'METLTonl' },
  { category: 'MOTORS', subCategory: 'ANTIQUE', catId: 'MOTRAntq' },
  { category: 'MOTORS', subCategory: 'COMBUSTION', catId: 'MOTRComb' },
  { category: 'MOTORS', subCategory: 'ELECTRIC', catId: 'MOTRElec' },
  { category: 'MOTORS', subCategory: 'MISC', catId: 'MOTRMisc' },
  { category: 'MOTORS', subCategory: 'SERVO', catId: 'MOTRSrvo' },
  { category: 'MOTORS', subCategory: 'TURBINE', catId: 'MOTRTurb' },
  { category: 'MOVEMENT', subCategory: 'ACTIVITY', catId: 'MOVEActv' },
  { category: 'MOVEMENT', subCategory: 'ANIMAL', catId: 'MOVEAnml' },
  { category: 'MOVEMENT', subCategory: 'CREATURE', catId: 'MOVECrea' },
  { category: 'MOVEMENT', subCategory: 'CROWD', catId: 'MOVECrwd' },
  { category: 'MOVEMENT', subCategory: 'HUMAN', catId: 'MOVEHmn' },
  { category: 'MOVEMENT', subCategory: 'INSECT', catId: 'MOVEInsc' },
  { category: 'MOVEMENT', subCategory: 'MISC', catId: 'MOVEMisc' },
  { category: 'MOVEMENT', subCategory: 'PRESENCE', catId: 'MOVEPres' },
  { category: 'MUSICAL', subCategory: 'BELLS', catId: 'MUSCBell' },
  { category: 'MUSICAL', subCategory: 'BRASS', catId: 'MUSCBrass' },
  { category: 'MUSICAL', subCategory: 'CHIME', catId: 'MUSCChim' },
  { category: 'MUSICAL', subCategory: 'CHORAL', catId: 'MUSCChor' },
  { category: 'MUSICAL', subCategory: 'EXPERIMENTAL', catId: 'MUSCExpr' },
  { category: 'MUSICAL', subCategory: 'INSTRUMENT', catId: 'MUSCInst' },
  { category: 'MUSICAL', subCategory: 'KEYED', catId: 'MUSCKeyd' },
  { category: 'MUSICAL', subCategory: 'LOOP', catId: 'MUSCLoop' },
  { category: 'MUSICAL', subCategory: 'MISC', catId: 'MUSCMisc' },
  { category: 'MUSICAL', subCategory: 'PERCUSSION', catId: 'MUSCPerc' },
  { category: 'MUSICAL', subCategory: 'PERCUSSION TUNED', catId: 'MUSCTnprc' },
  { category: 'MUSICAL', subCategory: 'PERFORMANCE', catId: 'MUSCPrfm' },
  { category: 'MUSICAL', subCategory: 'PLUCKED', catId: 'MUSCPluck' },
  { category: 'MUSICAL', subCategory: 'SAMPLE', catId: 'MUSCSmpl' },
  { category: 'MUSICAL', subCategory: 'SHAKEN', catId: 'MUSCShake' },
  { category: 'MUSICAL', subCategory: 'SONG & PHRASE', catId: 'MUSCSong' },
  { category: 'MUSICAL', subCategory: 'STINGER', catId: 'MUSCStngr' },
  { category: 'MUSICAL', subCategory: 'STRINGED', catId: 'MUSCStr' },
  { category: 'MUSICAL', subCategory: 'SYNTHESIZED', catId: 'MUSCSynth' },
  { category: 'MUSICAL', subCategory: 'TOY', catId: 'MUSCToy' },
  { category: 'MUSICAL', subCategory: 'WOODWIND', catId: 'MUSCWind' },
  { category: 'NATURAL DISASTER', subCategory: 'AVALANCHE', catId: 'NATDAval' },
  { category: 'NATURAL DISASTER', subCategory: 'EARTHQUAKE', catId: 'NATDQuak' },
  { category: 'NATURAL DISASTER', subCategory: 'MISC', catId: 'NATDMisc' },
  { category: 'NATURAL DISASTER', subCategory: 'TORNADO', catId: 'NATDTorn' },
  { category: 'NATURAL DISASTER', subCategory: 'TSUNAMI', catId: 'NATDTsun' },
  { category: 'NATURAL DISASTER', subCategory: 'TYPHOON', catId: 'NATDThyp' },
  { category: 'NATURAL DISASTER', subCategory: 'VOLCANO', catId: 'NATDVolc' },
  { category: 'OBJECTS', subCategory: 'BAG', catId: 'OBJBag' },
  { category: 'OBJECTS', subCategory: 'BOOK', catId: 'OBJBook' },
  { category: 'OBJECTS', subCategory: 'COIN', catId: 'OBJCoin' },
  { category: 'OBJECTS', subCategory: 'CONTAINER', catId: 'OBJCont' },
  { category: 'OBJECTS', subCategory: 'FASHION', catId: 'OBJFash' },
  { category: 'OBJECTS', subCategory: 'FURNITURE', catId: 'OBJFurn' },
  { category: 'OBJECTS', subCategory: 'GARDEN', catId: 'OBJGrdn' },
  { category: 'OBJECTS', subCategory: 'GYM', catId: 'OBJGym' },
  { category: 'OBJECTS', subCategory: 'HOUSEHOLD', catId: 'OBJHsehld' },
  { category: 'OBJECTS', subCategory: 'JEWELRY', catId: 'OBJJewl' },
  { category: 'OBJECTS', subCategory: 'KEYS', catId: 'OBJKey' },
  { category: 'OBJECTS', subCategory: 'LUGGAGE', catId: 'OBJLug' },
  { category: 'OBJECTS', subCategory: 'MEDICAL', catId: 'OBJMed' },
  { category: 'OBJECTS', subCategory: 'MISC', catId: 'OBJMisc' },
  { category: 'OBJECTS', subCategory: 'OFFICE', catId: 'OBJOffc' },
  { category: 'OBJECTS', subCategory: 'PACKAGING', catId: 'OBJPack' },
  { category: 'OBJECTS', subCategory: 'TAPE', catId: 'OBJTape' },
  { category: 'OBJECTS', subCategory: 'UMBRELLA', catId: 'OBJUmbr' },
  { category: 'OBJECTS', subCategory: 'WHEELED', catId: 'OBJWhled' },
  { category: 'OBJECTS', subCategory: 'WRITING', catId: 'OBJWrite' },
  { category: 'OBJECTS', subCategory: 'ZIPPER', catId: 'OBJZipr' },
  { category: 'PAPER', subCategory: 'FLUTTER', catId: 'PAPRFltr' },
  { category: 'PAPER', subCategory: 'FRICTION', catId: 'PAPRFric' },
  { category: 'PAPER', subCategory: 'HANDLE', catId: 'PAPRHndl' },
  { category: 'PAPER', subCategory: 'IMPACT', catId: 'PAPRImpt' },
  { category: 'PAPER', subCategory: 'MISC', catId: 'PAPRMisc' },
  { category: 'PAPER', subCategory: 'RIP', catId: 'PAPRRip' },
  { category: 'PAPER', subCategory: 'TONAL', catId: 'PAPRTonl' },
  { category: 'PLASTIC', subCategory: 'BREAK', catId: 'PLASBrk' },
  { category: 'PLASTIC', subCategory: 'CRASH & DEBRIS', catId: 'PLASCrsh' },
  { category: 'PLASTIC', subCategory: 'FRICTION', catId: 'PLASFric' },
  { category: 'PLASTIC', subCategory: 'HANDLE', catId: 'PLASHndl' },
  { category: 'PLASTIC', subCategory: 'IMPACT', catId: 'PLASImpt' },
  { category: 'PLASTIC', subCategory: 'MISC', catId: 'PLASMisc' },
  { category: 'PLASTIC', subCategory: 'MOVEMENT', catId: 'PLASMvmt' },
  { category: 'PLASTIC', subCategory: 'TONAL', catId: 'PLASTonl' },
  { category: 'RAIN', subCategory: 'CLOTH', catId: 'RAINClth' },
  { category: 'RAIN', subCategory: 'CONCRETE', catId: 'RAINConc' },
  { category: 'RAIN', subCategory: 'GENERAL', catId: 'RAIN' },
  { category: 'RAIN', subCategory: 'GLASS', catId: 'RAINGlas' },
  { category: 'RAIN', subCategory: 'INTERIOR', catId: 'RAINInt' },
  { category: 'RAIN', subCategory: 'METAL', catId: 'RAINMetl' },
  { category: 'RAIN', subCategory: 'PLASTIC', catId: 'RAINPlas' },
  { category: 'RAIN', subCategory: 'VEGETATION', catId: 'RAINVege' },
  { category: 'RAIN', subCategory: 'WATER', catId: 'RAINWatr' },
  { category: 'RAIN', subCategory: 'WOOD', catId: 'RAINWood' },
  { category: 'ROBOTS', subCategory: 'MISC', catId: 'ROBTMisc' },
  { category: 'ROBOTS', subCategory: 'MOVEMENT', catId: 'ROBTMvmt' },
  { category: 'ROBOTS', subCategory: 'VOCAL', catId: 'ROBTVox' },
  { category: 'ROCKS', subCategory: 'BREAK', catId: 'ROCKBrk' },
  { category: 'ROCKS', subCategory: 'CRASH & DEBRIS', catId: 'ROCKCrsh' },
  { category: 'ROCKS', subCategory: 'FRICTION', catId: 'ROCKFric' },
  { category: 'ROCKS', subCategory: 'HANDLE', catId: 'ROCKHndl' },
  { category: 'ROCKS', subCategory: 'IMPACT', catId: 'ROCKImpt' },
  { category: 'ROCKS', subCategory: 'MISC', catId: 'ROCKMisc' },
  { category: 'ROCKS', subCategory: 'MOVEMENT', catId: 'ROCKMvmt' },
  { category: 'ROCKS', subCategory: 'TONAL', catId: 'ROCKTonl' },
  { category: 'ROPE', subCategory: 'CREAK', catId: 'ROPECreak' },
  { category: 'ROPE', subCategory: 'HANDLE', catId: 'ROPEHndl' },
  { category: 'ROPE', subCategory: 'IMPACT', catId: 'ROPEImpt' },
  { category: 'ROPE', subCategory: 'MISC', catId: 'ROPEMisc' },
  { category: 'ROPE', subCategory: 'MOVEMENT', catId: 'ROPEMvmt' },
  { category: 'RUBBER', subCategory: 'CRASH & DEBRIS', catId: 'RUBRCrsh' },
  { category: 'RUBBER', subCategory: 'FRICTION', catId: 'RUBRFric' },
  { category: 'RUBBER', subCategory: 'HANDLE', catId: 'RUBRHndl' },
  { category: 'RUBBER', subCategory: 'IMPACT', catId: 'RUBRImpt' },
  { category: 'RUBBER', subCategory: 'MISC', catId: 'RUBRMisc' },
  { category: 'RUBBER', subCategory: 'MOVEMENT', catId: 'RUBRMvmt' },
  { category: 'RUBBER', subCategory: 'TONAL', catId: 'RUBRTonl' },
  { category: 'SCIFI', subCategory: 'ALARM', catId: 'SCIAlrm' },
  { category: 'SCIFI', subCategory: 'COMPUTER', catId: 'SCICmpt' },
  { category: 'SCIFI', subCategory: 'DOOR', catId: 'SCIDoor' },
  { category: 'SCIFI', subCategory: 'ENERGY', catId: 'SCIEnrg' },
  { category: 'SCIFI', subCategory: 'IMPACT', catId: 'SCIImpt' },
  { category: 'SCIFI', subCategory: 'MACHINE', catId: 'SCIMach' },
  { category: 'SCIFI', subCategory: 'MECHANISM', catId: 'SCIMech' },
  { category: 'SCIFI', subCategory: 'MISC', catId: 'SCIMisc' },
  { category: 'SCIFI', subCategory: 'RETRO', catId: 'SCIRetro' },
  { category: 'SCIFI', subCategory: 'SPACESHIP', catId: 'SCIShip' },
  { category: 'SCIFI', subCategory: 'VEHICLE', catId: 'SCIVeh' },
  { category: 'SCIFI', subCategory: 'WEAPON', catId: 'SCIWeap' },
  { category: 'SNOW', subCategory: 'CRASH & DEBRIS', catId: 'SNOWCrsh' },
  { category: 'SNOW', subCategory: 'FRICTION', catId: 'SNOWFric' },
  { category: 'SNOW', subCategory: 'HANDLE', catId: 'SNOWHndl' },
  { category: 'SNOW', subCategory: 'IMPACT', catId: 'SNOWImpt' },
  { category: 'SNOW', subCategory: 'MISC', catId: 'SNOWMisc' },
  { category: 'SNOW', subCategory: 'MOVEMENT', catId: 'SNOWMvmt' },
  { category: 'SPORTS', subCategory: 'COURT', catId: 'SPRTCourt' },
  { category: 'SPORTS', subCategory: 'FIELD', catId: 'SPRTField' },
  { category: 'SPORTS', subCategory: 'GYM', catId: 'SPRTGym' },
  { category: 'SPORTS', subCategory: 'INDOOR', catId: 'SPRTIndor' },
  { category: 'SPORTS', subCategory: 'MISC', catId: 'SPRTMisc' },
  { category: 'SPORTS', subCategory: 'SKATE', catId: 'SPRTSkate' },
  { category: 'SPORTS', subCategory: 'TRACK & FIELD', catId: 'SPRTTrck' },
  { category: 'SPORTS', subCategory: 'WATER', catId: 'SPRTWatr' },
  { category: 'SPORTS', subCategory: 'WINTER', catId: 'SPRTWntr' },
  { category: 'SWOOSHES', subCategory: 'SWISH', catId: 'SWSH' },
  { category: 'SWOOSHES', subCategory: 'WHOOSH', catId: 'WHSH' },
  { category: 'TOOLS', subCategory: 'GARDEN', catId: 'TOOLGrdn' },
  { category: 'TOOLS', subCategory: 'HAND', catId: 'TOOLHand' },
  { category: 'TOOLS', subCategory: 'MISC', catId: 'TOOLMisc' },
  { category: 'TOOLS', subCategory: 'PNEUMATIC', catId: 'TOOLPneu' },
  { category: 'TOOLS', subCategory: 'POWER', catId: 'TOOLPowr' },
  { category: 'TOYS', subCategory: 'ELECTRONIC', catId: 'TOYElec' },
  { category: 'TOYS', subCategory: 'MECHANICAL', catId: 'TOYMech' },
  { category: 'TOYS', subCategory: 'MISC', catId: 'TOYMisc' },
  { category: 'TRAINS', subCategory: 'BRAKE', catId: 'TRNBrake' },
  { category: 'TRAINS', subCategory: 'CLACK', catId: 'TRNClak' },
  { category: 'TRAINS', subCategory: 'DOOR', catId: 'TRNDoor' },
  { category: 'TRAINS', subCategory: 'DIESEL', catId: 'TRNDiesl' },
  { category: 'TRAINS', subCategory: 'ELECTRIC', catId: 'TRNElec' },
  { category: 'TRAINS', subCategory: 'HIGH SPEED', catId: 'TRNHspd' },
  { category: 'TRAINS', subCategory: 'HORN', catId: 'TRNHorn' },
  { category: 'TRAINS', subCategory: 'INTERIOR', catId: 'TRNInt' },
  { category: 'TRAINS', subCategory: 'MECHANISM', catId: 'TRNMech' },
  { category: 'TRAINS', subCategory: 'MISC', catId: 'TRNMisc' },
  { category: 'TRAINS', subCategory: 'STEAM', catId: 'TRNSteam' },
  { category: 'TRAINS', subCategory: 'SUBWAY', catId: 'TRNSbwy' },
  { category: 'TRAINS', subCategory: 'TRAM', catId: 'TRNTram' },
  { category: 'USER INTERFACE', subCategory: 'ALERT', catId: 'UIAlert' },
  { category: 'USER INTERFACE', subCategory: 'BEEP', catId: 'UIBeep' },
  { category: 'USER INTERFACE', subCategory: 'CLICK', catId: 'UIClick' },
  { category: 'USER INTERFACE', subCategory: 'DATA', catId: 'UIData' },
  { category: 'USER INTERFACE', subCategory: 'GLITCH', catId: 'UIGlitch' },
  { category: 'USER INTERFACE', subCategory: 'MISC', catId: 'UIMisc' },
  { category: 'USER INTERFACE', subCategory: 'MOTION', catId: 'UIMvmt' },
  { category: 'VEGETATION', subCategory: 'GRASS', catId: 'VEGEGras' },
  { category: 'VEGETATION', subCategory: 'LEAVES', catId: 'VEGELeaf' },
  { category: 'VEGETATION', subCategory: 'MISC', catId: 'VEGEMisc' },
  { category: 'VEGETATION', subCategory: 'TREE', catId: 'VEGETree' },
  { category: 'VEHICLES', subCategory: 'ALARM', catId: 'VEHAlrm' },
  { category: 'VEHICLES', subCategory: 'ANTIQUE', catId: 'VEHAntq' },
  { category: 'VEHICLES', subCategory: 'ATV', catId: 'VEHAtv' },
  { category: 'VEHICLES', subCategory: 'BICYCLE', catId: 'VEHBike' },
  { category: 'VEHICLES', subCategory: 'BRAKE', catId: 'VEHBrake' },
  { category: 'VEHICLES', subCategory: 'BUS', catId: 'VEHBus' },
  { category: 'VEHICLES', subCategory: 'CAR', catId: 'VEHCar' },
  { category: 'VEHICLES', subCategory: 'CONSTRUCTION', catId: 'VEHCnst' },
  { category: 'VEHICLES', subCategory: 'DOOR', catId: 'VEHDoor' },
  { category: 'VEHICLES', subCategory: 'ELECTRIC', catId: 'VEHElec' },
  { category: 'VEHICLES', subCategory: 'EMERGENCY', catId: 'VEHEmrg' },
  { category: 'VEHICLES', subCategory: 'FARM', catId: 'VEHFarm' },
  { category: 'VEHICLES', subCategory: 'FREIGHT', catId: 'VEHFrght' },
  { category: 'VEHICLES', subCategory: 'GENERIC BY', catId: 'VEHBy' },
  { category: 'VEHICLES', subCategory: 'HORN', catId: 'VEHHorn' },
  { category: 'VEHICLES', subCategory: 'INTERIOR', catId: 'VEHInt' },
  { category: 'VEHICLES', subCategory: 'JALOPY', catId: 'VEHJalop' },
  { category: 'VEHICLES', subCategory: 'MECHANISM', catId: 'VEHMech' },
  { category: 'VEHICLES', subCategory: 'MILITARY', catId: 'VEHMil' },
  { category: 'VEHICLES', subCategory: 'MISC', catId: 'VEHMisc' },
  { category: 'VEHICLES', subCategory: 'MOTORCYCLE', catId: 'VEHMoto' },
  { category: 'VEHICLES', subCategory: 'RACING', catId: 'VEHRace' },
  { category: 'VEHICLES', subCategory: 'SIREN', catId: 'VEHSirn' },
  { category: 'VEHICLES', subCategory: 'SKID', catId: 'VEHSkid' },
  { category: 'VEHICLES', subCategory: 'SUSPENSION', catId: 'VEHSusp' },
  { category: 'VEHICLES', subCategory: 'TIRE', catId: 'VEHTire' },
  { category: 'VEHICLES', subCategory: 'TRUCK VAN & SUV', catId: 'VEHTruck' },
  { category: 'VEHICLES', subCategory: 'UTILITY', catId: 'VEHUtil' },
  { category: 'VEHICLES', subCategory: 'WAGON', catId: 'VEHWagn' },
  { category: 'VEHICLES', subCategory: 'WINDOW', catId: 'VEHWndw' },
  { category: 'VOICES', subCategory: 'ALIEN', catId: 'VOXAlien' },
  { category: 'VOICES', subCategory: 'BABY', catId: 'VOXBaby' },
  { category: 'VOICES', subCategory: 'CHEER', catId: 'VOXCheer' },
  { category: 'VOICES', subCategory: 'CHILD', catId: 'VOXChld' },
  { category: 'VOICES', subCategory: 'CRYING', catId: 'VOXCry' },
  { category: 'VOICES', subCategory: 'EFFORTS', catId: 'VOXEfrt' },
  { category: 'VOICES', subCategory: 'FEMALE', catId: 'VOXFem' },
  { category: 'VOICES', subCategory: 'FUTZED', catId: 'VOXFutz' },
  { category: 'VOICES', subCategory: 'HISTORICAL', catId: 'VOXHist' },
  { category: 'VOICES', subCategory: 'LAUGH', catId: 'VOXLaff' },
  { category: 'VOICES', subCategory: 'MALE', catId: 'VOXMale' },
  { category: 'VOICES', subCategory: 'MISC', catId: 'VOXMisc' },
  { category: 'VOICES', subCategory: 'REACTION', catId: 'VOXReac' },
  { category: 'VOICES', subCategory: 'SCREAM', catId: 'VOXScrm' },
  { category: 'VOICES', subCategory: 'SINGING', catId: 'VOXSing' },
  { category: 'VOICES', subCategory: 'WHISPER', catId: 'VOXWhsp' },
  { category: 'WATER', subCategory: 'BUBBLES', catId: 'WATRBubl' },
  { category: 'WATER', subCategory: 'DRAIN', catId: 'WATRDran' },
  { category: 'WATER', subCategory: 'DRIP', catId: 'WATRDrip' },
  { category: 'WATER', subCategory: 'FIZZ', catId: 'WATRFizz' },
  { category: 'WATER', subCategory: 'FLOW', catId: 'WATRFlow' },
  { category: 'WATER', subCategory: 'FOUNTAIN', catId: 'WATRFoun' },
  { category: 'WATER', subCategory: 'IMPACT', catId: 'WATRImpt' },
  { category: 'WATER', subCategory: 'LAP', catId: 'WATRLap' },
  { category: 'WATER', subCategory: 'MISC', catId: 'WATRMisc' },
  { category: 'WATER', subCategory: 'MOVEMENT', catId: 'WATRMvmt' },
  { category: 'WATER', subCategory: 'PLUMBING', catId: 'WATRPlmb' },
  { category: 'WATER', subCategory: 'POUR', catId: 'WATRPour' },
  { category: 'WATER', subCategory: 'SPLASH', catId: 'WATRSplsh' },
  { category: 'WATER', subCategory: 'SPRAY', catId: 'WATRSpray' },
  { category: 'WATER', subCategory: 'STEAM', catId: 'WATRStm' },
  { category: 'WATER', subCategory: 'SURF', catId: 'WATRSurf' },
  { category: 'WATER', subCategory: 'TURBULENT', catId: 'WATRTurb' },
  { category: 'WATER', subCategory: 'UNDERWATER', catId: 'WATRUndwtr' },
  { category: 'WATER', subCategory: 'WATERFALL', catId: 'WATRFall' },
  { category: 'WATER', subCategory: 'WAVE', catId: 'WATRWave' },
  { category: 'WEAPONS', subCategory: 'ARMOR', catId: 'WEAPArmr' },
  { category: 'WEAPONS', subCategory: 'ARROW', catId: 'WEAPArro' },
  { category: 'WEAPONS', subCategory: 'AXE', catId: 'WEAPAxe' },
  { category: 'WEAPONS', subCategory: 'BLUNT', catId: 'WEAPBlnt' },
  { category: 'WEAPONS', subCategory: 'BOW', catId: 'WEAPBow' },
  { category: 'WEAPONS', subCategory: 'KNIFE', catId: 'WEAPKnif' },
  { category: 'WEAPONS', subCategory: 'MISC', catId: 'WEAPMisc' },
  { category: 'WEAPONS', subCategory: 'POLEARM', catId: 'WEAPPole' },
  { category: 'WEAPONS', subCategory: 'SIEGE', catId: 'WEAPSiege' },
  { category: 'WEAPONS', subCategory: 'SWORD', catId: 'WEAPSwrd' },
  { category: 'WEAPONS', subCategory: 'WHIP', catId: 'WEAPWhip' },
  { category: 'WEATHER', subCategory: 'HAIL', catId: 'HAIL' },
  { category: 'WEATHER', subCategory: 'MISC', catId: 'WTHR' },
  { category: 'WEATHER', subCategory: 'STORM', catId: 'STORM' },
  { category: 'WEATHER', subCategory: 'THUNDER', catId: 'THUN' },
  { category: 'WHISTLES', subCategory: 'HUMAN', catId: 'WHSTHmn' },
  { category: 'WHISTLES', subCategory: 'MECHANICAL', catId: 'WHSTMech' },
  { category: 'WHISTLES', subCategory: 'MISC', catId: 'WHSTMisc' },
  { category: 'WIND', subCategory: 'DESIGNED', catId: 'WINDDsgn' },
  { category: 'WIND', subCategory: 'GENERAL', catId: 'WIND' },
  { category: 'WIND', subCategory: 'GUST', catId: 'WINDGust' },
  { category: 'WIND', subCategory: 'INTERIOR', catId: 'WINDInt' },
  { category: 'WIND', subCategory: 'TONAL', catId: 'WINDTonl' },
  { category: 'WIND', subCategory: 'TURBULENT', catId: 'WINDTurb' },
  { category: 'WIND', subCategory: 'VEGETATION', catId: 'WINDVege' },
  { category: 'WINDOWS', subCategory: 'COVERING', catId: 'WNDWCover' },
  { category: 'WINDOWS', subCategory: 'HARDWARE', catId: 'WNDWHdwr' },
  { category: 'WINDOWS', subCategory: 'KNOCK', catId: 'WNDWKnck' },
  { category: 'WINDOWS', subCategory: 'METAL', catId: 'WNDWMetl' },
  { category: 'WINDOWS', subCategory: 'MISC', catId: 'WNDWMisc' },
  { category: 'WINDOWS', subCategory: 'PLASTIC', catId: 'WNDWPlas' },
  { category: 'WINDOWS', subCategory: 'WOOD', catId: 'WNDWWood' },
  { category: 'WINGS', subCategory: 'BIRD', catId: 'WINGBird' },
  { category: 'WINGS', subCategory: 'CREATURE', catId: 'WINGCrea' },
  { category: 'WINGS', subCategory: 'INSECT', catId: 'WINGInsc' },
  { category: 'WINGS', subCategory: 'MISC', catId: 'WINGMisc' },
  { category: 'WOOD', subCategory: 'BREAK', catId: 'WOODBrk' },
  { category: 'WOOD', subCategory: 'CRASH & DEBRIS', catId: 'WOODCrsh' },
  { category: 'WOOD', subCategory: 'FRICTION', catId: 'WOODFric' },
  { category: 'WOOD', subCategory: 'HANDLE', catId: 'WOODHndl' },
  { category: 'WOOD', subCategory: 'IMPACT', catId: 'WOODImpt' },
  { category: 'WOOD', subCategory: 'MISC', catId: 'WOODMisc' },
  { category: 'WOOD', subCategory: 'MOVEMENT', catId: 'WOODMvmt' },
  { category: 'WOOD', subCategory: 'TONAL', catId: 'WOODTonl' },
  { category: 'WOOD', subCategory: 'MISC', catId: 'WOODMisc' }
];

export const UCS_TOP_CATEGORIES: string[] = [
  'AIR',
  'AIRCRAFT',
  'ALARMS',
  'AMBIENCE',
  'ANIMALS',
  'ARCHIVED',
  'BEEPS',
  'BELLS',
  'BIRDS',
  'BOATS',
  'BULLETS',
  'CARTOON',
  'CERAMICS',
  'CHAINS',
  'CHEMICALS',
  'CLOCKS',
  'CLOTH',
  'COMMUNICATIONS',
  'COMPUTERS',
  'CREATURES',
  'CROWDS',
  'DESIGNED',
  'DESTRUCTION',
  'DIRT & SAND',
  'DOORS',
  'DRAWERS',
  'ELECTRICITY',
  'EQUIPMENT',
  'EXPLOSIONS',
  'FARTS',
  'FIGHT',
  'FIRE',
  'FIREWORKS',
  'FOLEY',
  'FOOD & DRINK',
  'FOOTSTEPS',
  'GAMES',
  'GEOTHERMAL',
  'GLASS',
  'GORE',
  'GUNS',
  'HORNS',
  'HUMAN',
  'ICE',
  'LASERS',
  'LEATHER',
  'LIQUID & MUD',
  'MACHINES',
  'MAGIC',
  'MECHANICAL',
  'METAL',
  'MOTORS',
  'MOVEMENT',
  'MUSICAL',
  'NATURAL DISASTER',
  'OBJECTS',
  'PAPER',
  'PLASTIC',
  'RAIN',
  'ROBOTS',
  'ROCKS',
  'ROPE',
  'RUBBER',
  'SCIFI',
  'SNOW',
  'SPORTS',
  'SWOOSHES',
  'TOOLS',
  'TOYS',
  'TRAINS',
  'USER INTERFACE',
  'VEGETATION',
  'VEHICLES',
  'VOICES',
  'WATER',
  'WEAPONS',
  'WEATHER',
  'WHISTLES',
  'WIND',
  'WINDOWS',
  'WINGS',
  'WOOD'
];

export function getSubCategories(category: string): string[] {
  const subCategories: string[] = [];
  for (const entry of UCS_CATEGORIES) {
    if (entry.category === category && !subCategories.includes(entry.subCategory)) {
      subCategories.push(entry.subCategory);
    }
  }
  return subCategories;
}

export function getCatId(category: string, subCategory: string): string | undefined {
  for (const entry of UCS_CATEGORIES) {
    if (entry.category === category && entry.subCategory === subCategory) {
      return entry.catId;
    }
  }
  return undefined;
}

export function generateUCSFilename(
  catId: string,
  fxName: string,
  creatorId?: string,
  sourceId?: string
): string {
  const parts = [catId, fxName];
  if (creatorId) {
    parts.push(creatorId);
    if (sourceId) {
      parts.push(sourceId);
    }
  } else if (sourceId) {
    parts.push('');
    parts.push(sourceId);
  }
  return parts.join('_');
}

export interface ParsedUCSFilename {
  catId: string;
  fxName: string;
  creatorId?: string;
  sourceId?: string;
  category?: string;
  subCategory?: string;
}

export function parseUCSFilename(filename: string): ParsedUCSFilename | null {
  // Strip extension
  const base = filename.replace(/\.[^/.]+$/, '');
  const parts = base.split('_');
  if (parts.length < 2) return null;

  const catId = parts[0];
  // Look up catId in UCS_CATEGORIES
  const entry = UCS_CATEGORIES.find(e => e.catId === catId);
  if (!entry) return null;

  return {
    catId,
    fxName: parts[1],
    creatorId: parts[2] || undefined,
    sourceId: parts[3] || undefined,
    category: entry.category,
    subCategory: entry.subCategory,
  };
}
